name: New event preparation
description: Create a request for new event
title: "##{%w{Jan Feb Mar Apr Jun Jul Aug Sep Nov Dec}} #{n}th Talk and socialize"
labels: [Talk]
assignees: []
body:
  - type: textarea
    id: link
    attributes:
      label: Event URL
      placeholder: "Exact event url can be found https://www.meetup.com/Elixir-Berlin/events/"
      value: "<TODO: https://www.meetup.com/Elixir-Berlin/events/gdsglryccnbsb/>"

  - type: textarea
    id: time
    attributes:
      label: Time
      placeholder: Date and time of the planned event
      value: "<TODO: eg. 14th October 7pm CEST>"

  - type: textarea
    id: location
    attributes:
      label: Location
      value: |
        - [ ] Remote/Hosting company

  - type: textarea
    id: talks
    attributes:
      label: Talks
      value: |
        - [ ] <talk name to be added>
        - [ ] <talk name to be added>
