name: Talk Proposal
description: Suggestion for a talk
title: "Talk Proposal #{your title here}"
labels: [Talk]
body:
  - type: input
    attributes:
      label: Your name
      placeholder: "José Valim"

  - type: input
    attributes:
      label: Your GitHub
      placeholder: "https://github.com/josevalim"
      
  - type: input
    attributes:
      label: Your Twitter (or other social link)
      placeholder: "https://twitter.com/josevalim"

  - type: input
    attributes:
      label: "Your proposal type: talk, lightning talk or til (today I learned)"
      placeholder: "talk"

  - type: input
    attributes:
      label: "Title of your presentation"
      placeholder: "Why Elixir is so amazing"
      
  - type: textarea
    attributes:
      label: Description
      placeholder: "In this talk I want to cover all the areas we love most about Elixir"

  - type: dropdown
    attributes:
      label: Favourite Month you would like to present in
      options: 
        - "Any/Next"
        - "January"
        - "February"
        - "March"
        - "April"
        - "May"
        - "June"
        - "July"
        - "August"
        - "September"
        - "October"
        - "November"
        - "December"

